version: '3'

services:
  gaiadnode0:
    container_name: pstakednode0
    image: "mkoijn6/pstakednode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-pstaked.log}
    volumes:
      - ./build:/pstaked:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  gaiadnode1:
    container_name: pstakednode1
    image: "mkoijn6/pstakednode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-pstaked.log}
    volumes:
      - ./build:/pstaked:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  gaiadnode2:
    container_name: pstakednode2
    image: "mkoijn6/pstakednode"
    environment:
      - ID=2
      - LOG=${LOG:-pstaked.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/pstaked:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  gaiadnode3:
    container_name: pstakednode3
    image: "mkoijn6/pstakednode"
    environment:
      - ID=3
      - LOG=${LOG:-pstaked.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/pstaked:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

